version: "3"

services:
  sql-server-db:
    container_name: sql-server-db
    build:
      context: .
      dockerfile: sql.Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "testPassword1"
      ACCEPT_EULA: "Y"
    volumes:
      - sql-server-volume:/var/opt/mssql/data

volumes: 
  sql-server-volume:
